version: "3.7"
services:
  foo-service:
    build:
      context: .
      dockerfile: foo.Dockerfile
    container_name: gotest-foo-service
    ports:
      - 8080:8080
    environment:
      - DBUSER=${DBUSER:-root}
      # - DBPASS=${DBPASS:?database password not set}
      - DBHOST=${DBHOST:-db}
      - DBPORT=${DBPORT:-26257}
      - DBNAME=${DBNAME:-mydb}
    deploy:
      restart_policy:
        condition: on-failure
